name: relief_web
description: A Future-based wrapper around the Relief Web API, to retrieve information on humanitarian news, reports, training, jobs, and disasters
version: 1.0.1
repository: https://github.com/0xdir/relief_web_dart

funding:
  - https://github.com/sponsors/0xdir
topics:
  - data
  - api
  - jobs
  - relief
  - humanitarian

environment:
  sdk: ^3.0.0

dependencies:
  connection: ^0.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0